site_name: atopile
site_url: https://atopile.io
site_description: >-
  Describe your circuit with code. Configure your design for your application.
  Reuse your past work. Share with your fellows using git. This is the promise of code to electronics.
  That is what we are here for. Introducing atopile!

nav:
- Home: index.md
- Getting started:
  - getting-started.md
- Packages:
  - blank: readme_blank.md
- Blog:
  - blog/index.md
plugins:
- drawio_file
- blog
repo_name: atopile/atopile
repo_url: https://github.com/atopile/atopile
site_name: atopile
theme:
  features:
  - navigation.tabs
  - navigation.sections
  - toc.follow
  #- header.autohide
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  custom_dir: docs/overrides
  logo: assets/ato_logo_256x256.png
  favicon: images/ato_logo_32x32.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

