name: Release VSCode Extension

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch: {}

jobs:
  vsx-extension:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/vscode-atopile
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      # Ensure the last tag was a valid version
      - run: git describe --tags --abbrev=0 | grep -q 'v[0-9]\+\.[0-9]\+\.[0-9]\+' || exit 1

      - name: Publish to VS Code Marketplace
        # Skip duplicate here to allow manual triggering
        run: npx vsce publish --no-git-tag-version --skip-duplicate ${$(git describe --tags --abbrev=0)#v}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX
        # version isn't needed here (nor possible?) because
        # it's already handelled by the vsce publish command
        # SKip duplicate here to allow manual triggering
        run: npx ovsx publish --skip-duplicate
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
